### ISSUE TITLE
 We're showing the time in ​*minutes*​ not seconds.

### ISSUE THREAD

**Issue by ezodude** [CardboardIoT/lightmeter#1]
The time shows 3m -> should be 3s.

**Comment by andrewn** [comment]
I can't seem to replicate this. Does this happen with the default exposures here?
   https://github.com/CardboardIoT/lightmeter/blob/master/static/src/conditions.js#L5-L81

The data in the exposure object should be in seconds that's then translated into minutes or hours for display if necessary.
