### ISSUE TITLE
When you cover the sensor: it shows ‘Direct sun’.

### ISSUE THREAD

**Issue by ezodude** [CardboardIoT/lightmeter#2]
It should be darker. Is it just the flakiness of the light resistor?

**Comment by andrewn** [comment]
`lightMeter.setLightLevel(value)` expects a number between 0-1 where 0 is darkness and 1 is brightness.

The light resistor does the opposite (darkness is 1, brightness is 0) [this code](https://github.com/CardboardIoT/smart-pinhole-workshop/blob/master/exercises/let_there_be_light/solution/solution.js#L22-L29) could flip the value to correct it before publishing e.g.

```
var value = (1 - this.value).toString()
```
