### ISSUE TITLE
Document all the things

### ISSUE THREAD

**Issue by ezodude** [CardboardIoT/lightmeter#3]
We need better documentation here. 
- A brief intro on how it works.
- We need to explain the APIs.
- Use cases for using it solo.

Can use MQTT documentation as a guideline: https://github.com/mqttjs/MQTT.js/blob/master/README.md

**Comment by andrewn** [comment]
I think I'm happy with [README.md](https://github.com/CardboardIoT/lightmeter/blob/master/README.md) now. It includes all the things in the list and a screenshot of the UI so will close this.
